export const actionTypes = {
    HTTP_CALL_END: 'HTTP_CALL_END',
    HTTP_CALL_START: 'HTTP_CALL_START',
    LOAD_PLAYER:'LOAD_PLAYER',
    LOAD_ID_PLAYER: 'LOAD_ID_PLAYER',
    ADD_PLAYER:'ADD_PLAYER',
    UPDATE_PLAYER:'UPDATE_PLAYER',
    DELETE_PLAYER:'DELETE_PLAYER'
  };
  